name: Keep Supabase Projects Alive

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Project 1
        run: |
          curl -X GET "https://knvotyfgzowdehvsvfgz.supabase.co/rest/v1/" \
            -H "apikey: sb_publishable_bribuFIcTF3X2PhdqWTG5Q_KuRNnC2m" \
            -H "Authorization: Bearer sb_publishable_bribuFIcTF3X2PhdqWTG5Q_KuRNnC2m"

      - name: Ping Project 2
        run: |
          curl -X GET "https://knvotyfgzowdehvsvfgz.supabase.co/rest/v1/" \
            -H "apikey: sb_publishable_nz2GDZj7lB4STIKbKoYa9w_Gin0zWRj" \
            -H "Authorization: Bearer sb_publishable_nz2GDZj7lB4STIKbKoYa9w_Gin0zWRj"

      - name: Ping Project 3
        run: |
          curl -X GET "https://knvotyfgzowdehvsvfgz.supabase.co/rest/v1/" \
            -H "apikey: sb_publishable_g3MePq5qGLgQ8tLUURbZbg_yqHZ7cgG" \
            -H "Authorization: Bearer sb_publishable_g3MePq5qGLgQ8tLUURbZbg_yqHZ7cgG"

      - name: Ping Project 4
        run: |
          curl -X GET "https://knvotyfgzowdehvsvfgz.supabase.co/rest/v1/" \
            -H "apikey: sb_publishable_6sv1VtrU9E8lElSQ32_F1A_Z-xFXqyi" \
            -H "Authorization: Bearer sb_publishable_6sv1VtrU9E8lElSQ32_F1A_Z-xFXqyi"
